#!/bin/bash
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
# Version: 2022-12-03
for keyval in  $(grep -E '": [^\{]' ./app/config/base.json | sed -e 's/: /=/' -e "s/\(\,\)$//"); do
    echo 'export ' $keyval && eval export $keyval
    #echo $keyval | sed 's/"//g' >> ./docker.env
done;

if [[ $baseElmer == "true" ]];
then
    noop
else
    cp ../elmer/app/routes/_routes.js ./app/routes/
    cp ../elmer/app/_app.js ./app/
    cp ../elmer/_index.js .
    cp ../elmer/_rebuilddocker.sh .
    cp ../elmer/_syncElmerBase.sh .
fi
